/*
 *  <@)
 *   KU//
 *   " "
 * KU 2026 -- make cool stuff!!
 *  by lucas frias
 *
 * human.c - EECS 348 Assignment 2
 * Description: Prioritizes a busy CEO's inbox using a MaxHeap (array/list based
 * priority queue) implemented entirely from scratch
 *Output: outputs specified in the PROMPT.md based on the rubric and instructions
 *
 * Author: Lucas Frias
 * Collaborators: Lucas, base implementation from Sonnet, debugging from Sonnet,
 * ZedAI autocomplete for some helper enum functions (notated below),
 * StackOverflow, specifically this post by Mr. Bharati:
 * https://stackoverflow.com/questions/30190460/advantages-of-strncmp-over-strcmp#30190652)
 * Inputs: a script file or stdin containing email commands
 * Created: September 4th 2026
 * Revised September 16th 2026 with recursive self analysis through LLMs
 * for better grading/formatting
 *
 * the rest is sonnet's prompt, i'll add it here for reasoning purposes
 * ============================================================
 * email_priority.c
 *
 * Prioritizes a busy CEO's inbox using a MaxHeap (array/list based
 * priority queue) implemented entirely from scratch -- no library
 * heap functions are used.
 *
 * Commands read from a script file (given as argv[1]) or stdin:
 *
 *   EMAIL <sender category>,<subject line>,<date MM-DD-YYYY>
 *   NEXT
 *   READ
 *   COUNT
 *
 * Sender category priority (highest to lowest):
 *   Boss > Subordinate > Peer > ImportantPerson > OtherPerson
 *
 * Within the same category, the NEWEST email (largest date) is
 * read first.
 * ============================================================ */

#include <cstdlib>
#include <stdio.h>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>
#include <ctype.h>
#include <stdbool.h>

/* ------------------------------------------------------------
 * Constants
 * ------------------------------------------------------------ */
//MAX_SUBJECT_LEN is the maximum length of a subject line
//INITIAL_CAPACITY is the initial capacity of the heap, can grow later
//GENERATED BY SONNET
#define MAX_SUBJECT_LEN   256
#define INITIAL_CAPACITY  16

//define sender ahead of time here
enum Sender {
    //we have to do these in reverse order so that boss is a higher number
    // enums start at 0, so boss is the highest value and we can use this to compare
    SenderUnknown,
    SenderOtherPerson,
    SenderImportantPerson,
    SenderPeer,
    SenderSubordinate,
    SenderBoss,
};
/* ------------------------------------------------------------
 * Email struct -- GENERATED BY SONNET, modified by Lucas
 * ------------------------------------------------------------ */
typedef struct {
    char subject[MAX_SUBJECT_LEN];     /* subject line                 */
    enum Sender categoryRank;                 /* enumerate priority of category */
    uint32_t dateValue;                    /* YYYYMMDD, for easy comparison */
} Email;

/* ------------------------------------------------------------
 * MaxHeap struct (list/array based implementation) -- GENERATED BY SONNET
 * ------------------------------------------------------------ */
typedef struct {
    Email *data;      /* dynamically allocated array of emails */
    int    size;      /* number of elements currently in heap  */
    int    capacity;  /* allocated capacity of the array       */
} MaxHeap;



/* ============================================================
 * Category priority lookup
 *
 * Higher number == higher priority (read sooner).
 * ============================================================ */

//ADDED BY LUCAS, changed from Sonnet's same function, used ZedAI autocomplete
enum Sender categoryRank(const char *category) {
    //categoryRank -> given a category string passed to us, we are able to
    // return the corresponding sender rank by using strcmp to compare the category
    // and returns the corresponding enum rank
    // if the category is not recognized, returns SenderUnknown, so super low
    // priority. also strcmp is safer because strncmp requires a length parameter
    // we're just checking for an exact match, so strcmp is fine
    if (strcmp(category, "Boss") == 0)            return SenderBoss;
    if (strcmp(category, "Subordinate") == 0)     return SenderSubordinate;
    if (strcmp(category, "Peer") == 0)            return SenderPeer;
    if (strcmp(category, "ImportantPerson") == 0) return SenderImportantPerson;
    if (strcmp(category, "OtherPerson") == 0)     return SenderOtherPerson;
    return SenderUnknown;
}


///ADDED BY LUCAS -> function to print the date. used ZedAI autocomplete
void printDate(uint32_t date) {
    //printDate -> given a uint32_t date value that represents a date
    // in just a number instead of bits, prints it as a formatted thing
    // e.g. 20240901 -> 09-01-2024
    // doesn't return anything, just prints to stdout

    //year, month, day we do some quick calculations
    // year we can integer divide to get
    int year = date / 10000;
    // month we can get by taking the remainder after dividing by 10000, then dividing by 100
    int month = (date % 10000) / 100;
    // day we can get by taking the remainder after dividing by 100
    int day = date % 100;
    //print it with the correct integer spacing
    printf("%02d-%02d-%04d", month, day, year);
}

//ADDED by Lucas - better printing for sender from enum - used ZedAI autocomplete
void printSender(enum Sender sender) {
    //printSender -> given an enum Sender value, prints the sender as a string
    // doesn't return anything, just prints the thingymajig
    switch (sender) {
        /*i'm gonna explain this so i don't gotta comment every
         * line because that's gotta be excessive, we just
         * basically match the enum value, and then when we get it
         * we can just printf for a value. we know that the enum
         * has to be within this range because we guarantee it
         * when we generate our categoryRank, so we don't need
         * a default case for this. we print using printf, and then
         * we break so we don't fall through to the next case
         */
        case SenderUnknown:
            printf("Unknown");
            break;
        case SenderBoss:
            printf("Boss");
            break;
        case SenderSubordinate:
            printf("Subordinate");
            break;
        case SenderPeer:
            printf("Peer");
            break;
        case SenderImportantPerson:
            printf("ImportantPerson");
            break;
        case SenderOtherPerson:
            printf("OtherPerson");
            break;
    }
    printf("\n");
}

/* ============================================================
 * Convert MM-DD-YYYY into a comparable integer YYYYMMDD.
 * Larger value == newer date.
 * ============================================================ */

//GENERATED BY SONNET
uint32_t dateToValue(const char *date) {
    //dateToValue - converts a date string in MM-DD-YYYY format to a comparable integer YYYYMMDD
    // returns it as a uint32_t to make sure we have enough space bc windows
    // sometimes does long as 4 bytes how scandalous
    //sonnet does a fancy int initialize in oneline
    int month = 0, day = 0, year = 0;
    //sscanf will try to cast the value from the date into the addresss
    // into like a reverse printf statement. if it returns 3, then we
    // know all three addresses got written to, but if it doesn't
    // sonnet kinda throws in the towel
    if (sscanf(date, "%d-%d-%d", &month, &day, &year) != 3) {
        return 0; /* malformed date, treat as very old */
    }
    //returns a uint32_t value representing the date in YYYYMMDD format
    // like how we said, we just added all of the values together up
    return ((uint32_t)year * 10000) + (month * 100) + day;
}

/* ============================================================
 * Compare two emails for max-heap ordering.
 * Returns 1 if "a" has strictly higher priority than "b", else 0.
 *
 * Priority rules:
 *   1) Higher categoryRank wins.
 *   2) If categories tie, newer date (larger dateValue) wins.
 * ============================================================ */
//generated completely by Sonnet except Lucas turned it fron int to bool
bool emailHasHigherPriority(const Email *a, const Email *b) {
    //bool emailHasHigherPriority - rates emails on the
    // priority rules defined in the assignment spec
    // takes two email pointers and returns true if "a" has higher priority than "b"
    if (a->categoryRank != b->categoryRank) {//check to see if they're not the same thing
        //oh cool they're not, that means we can just return whichever one has the greater category rank
        // btw this works like how the comp void ptr function works for
        // qsort in the ANSI C library where it returns a boolean for the sorting
        // just so happens that there are only two possibilities
        return a->categoryRank > b->categoryRank;
    }
    //now we just return the date value comparison if a < b
    return a->dateValue > b->dateValue;
}

/* ============================================================
 * MaxHeap creation / destruction
 * ============================================================ */

//generated by sonnet
MaxHeap *heapCreate(unsigned int initialCapacity) {
    //heapCreate - allocates and initializes a MaxHeap with the given capacity
    //returns a pointer to the newly created heap, or exits if memory allocation fails
    // initialCapacity: the initial capacity of the heap, although
    // i changed it to be an unsigned int because that makes more sense
    //
    //mild syntax edit, Sonnet did a recast even though it's a void pointer
    MaxHeap *heap = malloc(sizeof(MaxHeap));
    //okay now we check if we failed to make a heap. malloc will
    // return a pointer to 0 if it fails, so if we do !0 it will be
    // true
    if (!heap) {
        //now we freak out and exit with exit
        fprintf(stderr, "Fatal: out of memory creating heap.\n");
        exit(EXIT_FAILURE);
    }
    //now we allocate the backing array for the heap
    // i also removed the explicit cast to Email * again
    // more pedantic stuff
    heap->data = malloc(sizeof(Email) * initialCapacity);
    //same nullcheck we did for the heap pointer before
    if (!heap->data) {
        //same error handling we did for the heap pointer before
        // same old same old folks
        fprintf(stderr, "Fatal: out of memory allocating heap storage.\n");
        exit(EXIT_FAILURE);
    }
    //we need to remove the garbage stuff and explicitly initialize everythign
    heap->size = 0; //no elements yet set to zero
    heap->capacity = initialCapacity; //capacity is the default initial capacity
    return heap;//returns the heap pointer to the caller
}

//generated by Sonnet, slightly modified by Lucas
void heapDestroy(MaxHeap *heap) {
    //heapDestroy, given a heap pointer, free that guy
    // by first removing his data and then the heap itself
    if (!heap) return;//make sure the heap pointer is not null
    //and we're not dereferencing a null pointer
    if(!(heap->data)) return;//same thing here, this is ADDED BY LUCAS
    //sonnet never checked the data, but if we're checking the heap
    // pointer, we should check the data too, right?
    free(heap->data);//free the data first
    free(heap);//then the heap pointer, because otherwise we would have no pointer to free
}

/* Double the backing array when it fills up. */
//generated by Sonnet,
void heapEnsureCapacity(MaxHeap *heap) {
    //heapEnsureCapacity, given a heap pointer, double the capacity of the heap
    // very, very carefully
    // first check if the heap needs to be expanded this
    // function gets called every add which, is actually
    // really inefficient, but whatever guys
    if (heap->size < heap->capacity) return;
    //okay now we double the capacity value. we actually don't check
    // for integer overflow here, but if the capacity is too large,
    // but whatever right, it would be hard to exceed that (maybe)
    int newCapacity = heap->capacity * 2;
    //get the newData pointer, which is the realloce memory block. We have
    // to do this explicitly to get the same contigious block of memory
    // that we started with, so we can free it later without issues
    // i also modified the realloc call to use the same type as the original
    // data pointer, so we don't have to cast it back to Email* later
    Email *newData = realloc(heap->data, sizeof(Email) * newCapacity);
    //check if the realloc call succeeded, and exit if it didn't
    // it's just making sure we don't have a null pointer
    if (!newData) {
        //exit out and whine to the usre
        fprintf(stderr, "Fatal: out of memory growing heap.\n");
        exit(EXIT_FAILURE);
    }
    //set the data pointer to the new memory blocks, nothing fancy here
    heap->data = newData;
    heap->capacity = newCapacity;
}

/* ------------------------------------------------------------
 * Index helpers for the array-based (list-based) heap layout.
 * For node at index i (0-based):
 *   parent  = (i - 1) / 2
 *   left    = 2*i + 1
 *   right   = 2*i + 2
 * ------------------------------------------------------------ */


//all of these functions are generated by sonnet, but i added inline
// to improve performance by avoiding function call overhead.
// makes it a tiny bit faster
inline static int parentIndex(int i) { return (i - 1) / 2; }
inline static int leftChildIndex(int i)  { return 2 * i + 1; }
inline static int rightChildIndex(int i) { return 2 * i + 2; }

//this function is pure sonnet
static void swapEmails(Email *a, Email *b) {
    //just swaps the contents of two Email pointers,
    //no need to copy the entire struct
    Email temp = *a;
    *a = *b;
    *b = temp;
}

/* ------------------------------------------------------------
 * Sift-up (bubble-up): restores heap property after insertion
 * at the end of the array.
 * ------------------------------------------------------------ */

//this is sonnet
void heapSiftUp(MaxHeap *heap, int index) {
    //heapSiftUp - given a maxheap and an index where we start,
    //bubble up the element to its correct position
    while (index > 0) { //because we would stop at zero right
        int parent = parentIndex(index);//get the parent index, the higher node
        //check the priority based on our dada
        if (emailHasHigherPriority(&heap->data[index], &heap->data[parent])) {
            //is out dada higher than us? then swap
            // and we become the alpha (we are the parent
            // and they are our child)
            swapEmails(&heap->data[index], &heap->data[parent]);
            //and keep bubbling up
            index = parent;
        } else {
            //we're done! we can stop sifting up
            break;
        }
    }
}

/* ------------------------------------------------------------
 * Sift-down (bubble-down): restores heap property after the
 * root is replaced (e.g. during extraction).
 * ------------------------------------------------------------ */

//generated by sonnet
void heapSiftDown(MaxHeap *heap, int index) {
    //heapSiftDown - given a maxheap pointer
    // and an index where we star
    //bubble down the element to its correct position
    // this happens after a pop and we need to re-order

    //keep bubbling down until we find the correct position
    while (true) {

        //find the largest of the current node and its children
        //first get our left and right
        int left  = leftChildIndex(index);
        int right = rightChildIndex(index);
        //then get our index, set it to the largets
        int largest = index;

        //if the largest is not the current node, swap and continue
        if (left < heap->size &&
            emailHasHigherPriority(&heap->data[left], &heap->data[largest])) {
            largest = left;
        }
        //do the same but for the right, we change our stuff
        if (right < heap->size &&
            emailHasHigherPriority(&heap->data[right], &heap->data[largest])) {
            largest = right;
        }
        //if we neither need to go left or right, then we break
        // because we are now reorganized
        if (largest == index) break;
        //swap with the largest child because we found a new largest value
        swapEmails(&heap->data[index], &heap->data[largest]);
        //set the index to be the largest
        index = largest;
    }
}

/* ------------------------------------------------------------
 * Insert a new email into the heap.
 * ------------------------------------------------------------
 * heapInsert is generated by Sonnet*/
void heapInsert(MaxHeap *heap, Email email) {
    //heapInsert, given a maxheap pointer and an email,
    //just throw it into the heap at the i+heapsize position and
    // then heapShift it up to the correct position starting
    // from it's i+heapsize position

    heapEnsureCapacity(heap);//first make sure we have enough space
    heap->data[heap->size] = email; //second set the email at the new position
    heapSiftUp(heap, heap->size); //now we sift all the way up
    heap->size++;//we increment the size because we added a new element and for the next insert
}

/* ------------------------------------------------------------
 * Peek at the highest-priority email without removing it.
 * Returns 1 on success, 0 if heap is empty.
 * ------------------------------------------------------------ */

//generated by Sonnet, bool by Lucas
bool heapPeek(MaxHeap *heap, Email *outEmail) {
    //heapPeek, given a maxheap ptr and a email ptr, return a boolean
    // of the success at writing the out email
    if (heap->size == 0) return false; //we can't peek nothing
    *outEmail = heap->data[0];//set the value
    return true;//return a boolean value that says yay!! we did it
}

/* ------------------------------------------------------------
 * Remove and return the highest-priority email.
 * Returns 1 on success, 0 if heap is empty.
 * ------------------------------------------------------------ */
//generated by Sonnet, bool by Lucas
bool heapExtractMax(MaxHeap *heap, Email *outEmail) {
    //heapExtractMax, given a maxheap ptr and a email ptr, return a boolean
    // of the success of us getting the Max value (the top). we
    // write it to outEmail and then remove it from the heap
    // because of the read thingamajigger
    if (heap->size == 0) return false;

    //extract the max value (the top) and write it to outEmail
    *outEmail = heap->data[0];
    //deincrement our heap
    heap->size--;

    if (heap->size > 0) {//make sure we don't try and sift down
        //a zero sized heap
        //now we set the top to the last element in the heap
        heap->data[0] = heap->data[heap->size];
        //we need to resift down and compare every index
        // and make sure they preserve the order
        heapSiftDown(heap, 0);//starting at our new head
    }
    return true;
}

//generated by sonnet, made a tiny bit safer by lucas
int heapSize(MaxHeap *heap) {
    //given a hea ptr, return the size of the heap
    if (!heap) return 0;//return 0 for an uninit heap (nullptr)
    return heap->size;//return the heapsize
}

/* ============================================================
 * String helpers
 * ============================================================ */

/* Strip trailing newline / carriage return characters. */
//generated by sonnet,
void trimNewline(char *s) {
    //trimNewline, given a char * s, let's remove every
    // single newline and tab or whatever other formatting nonsense
    //first, let's get the len of the str
    size_t len = strlen(s);
    //now, let's loop through the str, removing any trailing newlines
    // basically, while our len is greater than 0 and our last char is
    // a newline or tab character
    // we remove it and decrement our len by one.
    // this is only for the end of the line, very specifically
    // for the sender/subject
    while (len > 0 && (s[len - 1] == '\n' || s[len - 1] == '\r')) {
        s[len - 1] = '\0';
        len--;
    }
    //the pointer is the one being worked on, so we don't have to do anything
}

/* Remove leading/trailing whitespace in place. */
//generated by sonnet, imrproved by lucas
void trimWhitespace(char *s) {
    //trimWhitespace, given a char * s, deletes
    // all spacin characters in a confusing way
    /* Trim trailing */
    //fixed by lucas to use size_t, but get the strlen
    size_t len = (size_t)strlen(s);
    //now we loop while we still have a len, and we check if
    // the char is a space with isspace from the part
    //this part removes the trailing (end part) whitespace
    while (len > 0 && isspace((unsigned char)s[len - 1])) {
        s[--len] = '\0';
    }
    /* Trim leading */
    //^^ yeah what sonnet said, but we keep track and
    // then memcpy later you'll see
    int start = 0;
    while (s[start] != '\0' && isspace((unsigned char)s[start])) {
        //loop while we still have a char and it's a space, add for start
        start++;
    }
    if (start > 0) {
        //kinda recopy the string over itself from the start
        // before there's any spaces, pretty sick
        memmove(s, s + start, strlen(s + start) + 1);
    }
}

/* ============================================================
 * Parse an "EMAIL <category>,<subject>,<date>" line (the text
 * AFTER the leading "EMAIL " token has already been stripped
 * off by the caller) into an Email struct.
 *
 * Returns 1 on success, 0 on a malformed line.
 * ============================================================ */
//generated by sonnet, fixed a bit by lucas
bool parseEmailFields(char *fields, Email *outEmail) {
    //parseEmailFields, given a char * to the email field statement
    // generated an Email and return it
    /* fields looks like: "Boss,Never Mind,01-03-2025" */
    //first let's split with the first comma
    char *firstComma = strchr(fields, ',');
    //if this can't happen, the line is malformed return
    if (!firstComma) return false;
    //we set the split part, instead of being a comma, to
    // a null term so we can reinterpert it as a value later
    // we basically mutate the string with a bunch of
    // null terms and then read from the ptrs so we get
    // Boss \oNever Mind\0 01-03-2025\0 or something like that
    *firstComma = '\0';
    char *category = fields;//set category to the first part, this is
    //just the beginning base pointer
    char *rest = firstComma + 1;//we do pointer arithematic for the
    //second part of the string
    char *secondComma = strrchr(rest, ','); /* subject can't have commas,
                                                so the LAST comma in the
                                                remainder separates the
                                                subject from the date */
    if (!secondComma) return false;//same error check as before
    *secondComma = '\0';//set the second part to a null term so we can
    //read it as a value later
    char *subject = rest;//set our pointer to the start after the first null term
    char *date = secondComma + 1;//the date is the rest
    //we don't need to parse again, this is the last field and it is already
    // null terminated

    //remove all the whitespace from the fields, passing
    // our pointer and letting them do work
    trimWhitespace(category);
    trimWhitespace(subject);
    trimWhitespace(date);

    //check for malfomed or empty fields and return a false
    //if one or the other is empty, the line is malformed
    if (strlen(category) == 0 || strlen(date) == 0) return false;

    //okay now we can safely parse the fields, first we get the category
    // rank as an enum value
    outEmail->categoryRank = categoryRank(category);

    //now we copy the subject into the email struct, making sure to
    // null terminate it and do truncation if necessary when it
    // exceeds the maximum subject length
    strncpy(outEmail->subject, subject, MAX_SUBJECT_LEN - 1);
    //add that pesky null term character to the end, just in case
    outEmail->subject[MAX_SUBJECT_LEN - 1] = '\0';
    //set the date value by calling dateToValue on the date string,
    //sets the uint32_t date value for easy comparison
    outEmail->dateValue = dateToValue(date);
    return true;//return boolean signaling we did it
}

/* ============================================================
 * Command handlers
 * ============================================================ */
//generated by sonnet
void handleEmailCommand(MaxHeap *heap, char *line) {
    //handleEmailCommand: given a heap ptr, and an EMAIL line, interperts
    // what to do with the values given from each line

    /* line begins with "EMAIL ", the rest is the field data */
    char *fields = line + strlen("EMAIL");
    //fixes formatting ehre
    while (*fields == ' ') fields++; /* skip the single space (and any extra) */

    Email email;//make a new email here
    //if we return a false value, meaning we couldn't parse the fields,
    //we print an error message and return
    if (!parseEmailFields(fields, &email)) {
        //throw an error
        fprintf(stderr, "Warning: could not parse EMAIL line: %s\n", line);
        return;
    }
    //insert our email into the heap, pass by value
    heapInsert(heap, email);
}

void handleNextCommand(MaxHeap *heap) {
    //handleNextCommand: given a heap ptr, prints the next email in the heap
    //if there are no emails, prints a message and returns
    Email top;
    //if we have false, that means our heap is of size 0
    if (!heapPeek(heap, &top)) {
        printf("Next email:\n");
        printf("There are no emails to read.\n\n");
        //premature return to avoid next steps
        return;
    }
    //alright now we have an email to print
    printf("Next email:\n");
    printf("Sender: ");
    //display the sender as a string from the enum value
    printSender(top.categoryRank);
    //print the subject, it's just a string so we use %s
    printf("Subject: %s\n", top.subject);
    //print the date, it's a uint32_t reverse formatted
    // so we use that special printDate
    printf("Date: ");
    printDate(top.dateValue);
    printf("\n\n");

}

void handleReadCommand(MaxHeap *heap) {
    //handleReadCommand, given a maxheap *, removes the top email and prints it
    // first we check if there's anything to remove
    Email dequeued;
    //check to make sure there's something to remove
    // heapExtractMax will also print the info if it
    // exists, so not handled here
    // actually don't know why we have the dequeued thing
    // to begin with it's kinda pointless except for having
    // some address to write to
    if (!heapExtractMax(heap, &dequeued)) {
        printf("There is nothing to mark as read.\n\n");
    }
    /* Per spec, READ simply removes the current top email
       (the CEO dealt with it). No output is required. */
    //this is sonnets note here, and it's true ^^
}

void handleCountCommand(MaxHeap *heap) {
    //handleCountCommand, given a maxheap *, prints the number of emails to read
    //we just print the integer version of the heap size
    printf("There are %d emails to read.\n\n", heapSize(heap));
}

/* ============================================================
 * Main driver: reads commands line by line from the given file
 * (or stdin if no file argument is provided) and dispatches
 * them to the appropriate handler.
 * ============================================================ */

//main, generated by sonnet
int main(int argc, char *argv[]) {
    //main, given a file argument, reads commands from the file
    // and sends those guys to the appropriate handler
    FILE *input = stdin;//get the file from the command line

    //make sure we have enough arguments
    //i modified this to make sure it's the one file
    // because that's the only support we have
    if (argc == 2) {
        //now let's try and open the file
        input = fopen(argv[1], "r");
        //if the input is null, we couldn't open the file (nullptr)
        if (!input) {
            //freak out!!
            fprintf(stderr, "Error: could not open file '%s'\n", argv[1]);
            return EXIT_FAILURE;
        }
    }
    else{printf("Error! Please include a file\n"); return EXIT_FAILURE;}

    //now let's create the heap, using our initial capacity macro
    MaxHeap *heap = heapCreate(INITIAL_CAPACITY);

    char line[1024];//allocate space for the line to interpet
    //fgets reads a line from the file into the buffer
    while (fgets(line, sizeof(line), input)) {
        //remove the newline stuff
        trimNewline(line);
        //added by lucas inspired by sonnet's past error checking
        // seems smart to make usre
        line[1023] = '\0';

        /* Skip blank lines */
        char *check = line;
        //skip leading whitespace on the thing, by incrementing
        // our check pointer by 1 if we have them
        while (*check == ' ' || *check == '\t') check++;
        if (*check == '\0') continue;//break out of this
        //iteration because it's an empty line

        /* big comment here,
         * okay so we have a line, let's check what it is
         * we incremented all the way to the point where
         * there is no longer any whitespace, so now we
         * have a non-empty line to work with. it might
         * be an EMAIL, NEXT, READ, or COUNT command
         * or it might not be at all. the way sonnet validates
         * this is by just check the first N characters,
         * where N is the length of the command string that
         * could or could not be there. this avoids the
         * error with strcmp that Luna had with some weird
         * whitespace characters at the end of the line
         * that would mess up its jam. we just hand
         * it off to its approrpiate helper command.
         * 0 means no error, and then i'll describe what
         * each helper command does.
         */
        if (strncmp(line, "EMAIL", 5) == 0) {
            //adds an email to the heap
            handleEmailCommand(heap, line);
        } else if (strncmp(line, "NEXT", 4) == 0) {
            //prints the next email in the heap
            handleNextCommand(heap);
        } else if (strncmp(line, "READ", 4) == 0) {
            //removes the top email and prints it
            handleReadCommand(heap);
        } else if (strncmp(line, "COUNT", 5) == 0) {
            //prints the number of emails left to read
            handleCountCommand(heap);
        } else {
            //prints an error message for unrecognized commands
            fprintf(stderr, "Warning: unrecognized command: %s\n", line);
        }
    }

    if (input != stdin) {
        //close our input file
        fclose(input);
    }
    //free the heap and all its memory
    heapDestroy(heap);
    //we did it!! return success
    return EXIT_SUCCESS;
}
